package com.spectralogic.tpfr.client;

import com.spectralogic.tpfr.api.response.IndexStatus;
import com.spectralogic.tpfr.api.response.OffsetsStatus;
import com.spectralogic.tpfr.client.model.QuestionTimecodeParams;

public interface Client {
    /**
     * This method will block while the index is created and will only return when either the index file has been created or for some reason it has not been possible to create the index file.
     * On HFS systems that leave stub files on disk, such as StorNext, if a request is made to create an index for a media file which has been truncated by StorNext, this call will cause the entire media file to be restored by StorNext.
     * The Web Service will support multiple concurrent calls to this command.
     * @param filePath The full path (via a mapped drive on the StorNext MDC) to the media file to be indexed.
     * @return @see {@link IndexStatus}
     * @throws Exception
     */
    IndexStatus indexFile(final String filePath) throws Exception;

    /**
     * This method will block while retrieving the index status for a previously indexed file.
     * This method internally uses an XML file, generated by the indexer to retrieve the detailed status.This XML file is only generated by Quantum PFR version 1.1 and later.For files that were indexed in an earlier version of Quantum PFR, minimal information will be retrieved (just whether the file had been indexed or not).
     * The Web Service will support multiple concurrent calls to this API call.
     * @param filePath The full path (via a mapped drive on the StorNext MDC) to the media file whose status is to be retrieved.
     * @return @see {@link IndexStatus}
     * @throws Exception
     */
    IndexStatus fileStatus(final String filePath) throws Exception;

    /**
     * This method will block whilst retrieving the start and end byte offsets for the requested timecodes. The offsets are extended in order to handle GOP and interleave ordering.
     * Timecode format should be in form hh:mm:ss:ff for non-drop framerates and hh:mm:ss;ff for drop framerates.
     * If the tcout requests the last frame or beyond from the source the return will give ‘0xffffffffffffffff’.
     * @param params @see {@link QuestionTimecodeParams}
     * @return
     */
    OffsetsStatus QuestionTimecode(QuestionTimecodeParams params) throws Exception;
}
